### ISSUE TITLE
Proper express syntax for slide_player

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#112]
Support short syntax for slide_player:

Instead of:

```
slide_player:
  tilt: slide_22
  tilt_clear:
    slide_22: 
      action: remove
```

this should also work:

```
slide_player:
  tilt: slide_22
  tilt_clear:
    slide_22: remove
```
