### ISSUE TITLE
wrong video being played when prior video with higher priority was played

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#165]
From Brian Cox:

```
widgets:
 widgetVideo2X:
   - type: video
     video: 2X
     z: 140
   - type: image
     image: yellowFrame
     z: 145
     opacity: 0
     animations:
       entrance:
         - property: opacity
           value: 1
           duration: 0.5s

 widgetVideo4X:
   - type: video
     video: 4X
     z: 130

 widgetVideo8X:
   - type: video
     video: 8X
     z: 120

 widgetVideo16X:
   - type: video
     video: 16X
     z: 110
```

...and then widget_player looks like this:

```
widget_player:

 eventCollectBonusText:
   widgetCollectBonusText:
     widget_settings:    
       expire: 4s
     slide: collectbonus_slide_1

 eventCollect2xWidget: 
   widgetVideo2X:
     widget_settings:    
       expire: 8s
     slide: collectbonus_slide_1

 eventCollect4xWidget: 
   widgetVideo4X:
     widget_settings:    
       expire: 8s
     slide: collectbonus_slide_1

 eventCollect8xWidget: 
   widgetVideo8X:
     widget_settings:    
       expire: 8s
     slide: collectbonus_slide_1
```

"If I only call the "2X" event, that video plays, but once I call "2X" and then "4X", the "4X" will always play when "2X" should be playing.

And then once I call the sequence "2X", "4X", "8X", from then on, "8X" gets played instead of "2X" every time that the "2X" event is called... and so on and so on up to "64X".

Whatever video was the last one played in that "slide" ends up getting played first the next time that slide is displayed. This is across shows...

Or, more precisely, whatever video that was played with the _highest priority_ in the past, ends up being repeated the next time the slide is shown.

 just to clarify, by priority I actually mean "z" height

Mark "Your 2x video maybe playing behind the 4x"

Brian Cox "It is, but that's by intention... but the next time that mode is started and the slide displayed, the lowest Z order video from the last time the mode was active somehow takes the spot of the 2X show. The next time I enter the mode, the first widget is always the _historically_ lowest Z."
