### ISSUE TITLE
slide added with expire kills slide below it from same mode

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#181]
This is part of the general tweaking of slides.

base mode config, priority 100:

```
  player_add_success:
    player_added:
      priority: 101

slides:

  player_added:
    type: text
    text: PLAYER (num) ADDED
    expire: 2s
```

Slide for the player added works, but the base mode score slide does not show when the player added slide expires. Could be that it's being deleted, or who knows. But it shouldn't work this way.
