### ISSUE TITLE
Sound stop events not posting in MC

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-mc#198]
When a sound's events_when_stopped event is configured, MC sends a trigger to MPF, and MPF posts and responds to the event. MC doesn't post the event at all, so it can't respond to it.

**Comment by qcapen** [comment]
This has already been fixed in 0.32, but not backported to 0.31.  Looks like a very simple change to backport to get it fixed, although cherry picking will not be easy because of the other changes that were included in the commit (bfa1c533707d80fc7950d437983ade4c50d4faed). Can make the changes manually if necessary.

**Comment by qcapen** [comment]
I'm mistaken.  It was fixed in 0.31.8 (b6bbfd3157e38df43fb9d8c7fa6930ad9a739316).  Are you running 0.31.8 and it is not working for you?

**Comment by GabeKnuth** [comment]
I'm running 0.32.0-dev7. I also don't see loop events. I know all of these worked at one point, but I think I was using a feature branch before it was committed into dev.

Here's my config:

```
sound_player:
  mode_base_started:
    wait_to_plunge:
        action: play
        loops: -1
        events_when_looping: wait_to_plunge_looped
  balldevice_bd_plunger_ball_left:
    plunged:
        action: play
        loops: 0
        events_when_stopped: start_step_3
    wait_to_plunge:
        action: stop
  start_step_3:
    base_bed_loop:
        action: play
        loops: -1
```

When mode_base_started posts, it plays the "wait_to_plunge" sound just fine, but the wait_to_plunge_looped event does not post.

When I plunge and balldevice_bd_plunger_ball_left posts, the "plunged" sound plays, but when it stops, the start_step_3 event doesn't post (which means the third song, "base_bed_loop" doesn't play).

Brian said he'd look later, too, but that will likely be Monday night. 

Not sure if it helps to try my game? If it does, you can see it https://github.com/gabeknuth/bnd
