### ISSUE TITLE
Add ability to fade out videos

### ISSUE THREAD

**Issue by GabeKnuth** [missionpinball/mpf-mc#203]
I don't see this in the config spec, so I'm guessing it doesn't exist. There isn't a way to fade out a video. In Brooks & Dunn, there are music videos running in each mode, and when the mode ends the videos just abruptly stop. I'd like to see something like the fade_in and fade_out in the sound player. 

If this isn't a hackathon thing, maybe there's a workaround?

**Comment by toomanybrians** [comment]
I assume we just need to add something for audio? Since video fading can happen with the standard widget/slide animations and transitions?

**Comment by toomanybrians** [comment]
Actually, volume is just a property of a widget, so that should be animate-able. I'll try it now

**Comment by toomanybrians** [comment]
Using the widget animation with the volume property works like a charm! I'm going to close this.

Here's what I added to the slide to fade out the video. Just the animations: section is new:

```
slides:
  world_tour_stage:
    widgets:
      - type: video
        video: wt_boot_scoot
        end_behavior: loop
        animations:
          world_tour_fade_out:
            - property: volume
              value: 0
              duration: 2s
```

Since there was already an event player to stop the mode, I just added another one to start the fade out:

```
event_player:
  shot_australia_hit:
    world_tour_done|5s
    world_tour_fade_out|3s
```
