### ISSUE TITLE
Use named widget during slide creation?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#233]
Currently it's only possible to use a named widget with the widget_player. But what if you want to define a slide and use a named widget?

Most likely due to the syntax differences, we'd have to create a new "type" of widget and end up doing something like this:

```
slides:
  my_slide:
    - type: text
      text: Hello
    - type: named_widget
      widget: my_widget
```

Further settings there could be used to update/overwrite named widget settings
