### ISSUE TITLE
Video control events crashing?

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#240]
Why doesn't this work?

```
- duration: 5s
  slides:
      game_logo_slide:
          widgets:
          - type: video
            video: game_attract

            control_events:
            - event: pre_show_slide
              action: seek
              value: 0.00
            - event: pre_show_slide
              action: play
            z: 24
            end_behavior: stop
          transition:
            type: move_in
            duration: 1s
            direction: bottom
```
