### ISSUE TITLE
Use proper yaml lists for all pools

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#252]
Currently we propose this in the docs:

```
sound_pools:
   drain_callout:
      type: random_force_all
      sounds:
         drain_01
         drain_02
         drain_03
         drain_04
```

This works but e.g. if you want to use a sound with spaces like "your sound" it will break. This would be better:

```
sound_pools:
   drain_callout:
      type: random_force_all
      sounds:
         - drain_01
         - drain_02
         - "drain 03" # example for a space
         - "drain 04"
```

http://docs.missionpinball.org/en/latest/config/sound_pools.html
