### ISSUE TITLE
Allow template for master_volume and volume in sound system

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#271]
```
sound_system:
    buffer: 2048
    channels: 2
    enabled: True
    frequency: 44100
    master_volume: machine.master_volume     # example with machine var
    tracks:
       music:
          simultaneous_sounds: 2
          volume: settings.volume_music     # example with settings
       voice:
          simultaneous_sounds: current_player.voice_volume   # example with player var (does not make much sense)
          volume: 1                                     # just a plain float value
       sfx:
          simultaneous_sounds: 5
          volume: devices.counters.my_counter.value       # example with counter logic block
```
