### ISSUE TITLE
Ducking seems to work globally

### ISSUE THREAD

**Issue by jabdoa2** [missionpinball/mpf-mc#315]
My sound config looks like this:
```
sound_system:
  tracks:
    voice:
      volume: 0.9
      priority: 2
      simultaneous_sounds: 1
      preload: true
      ducking:
        target: music
        delay: 0
        attack: 0.3 sec
        attenuation: 0.45
        release_point: 0.5 sec
        release: 1.0 sec
    sfx:
      volume: 0.9
      priority: 1
      preload: true
      simultaneous_sounds: 3
    music:
      volume: 0.4
      simultaneous_sounds: 1
  buffer: 2048  # previous value was 512
  frequency: 44100
  channels: 1
  master_volume: 0.8
  enabled: true
```

Ducking works fine and sounds awesome for all callouts. However, I noticed that it also applies to all my sounds in the sfx track. When I remove ducking for callouts it also disappears for sfx. Any idea why that happens and how to fix it?

**Comment by qcapen** [comment]
I'm surprised it works at all assigning it at the track level as it is a sound asset property and not associated with any track attributes.  

How about assigning it in the default asset settings as follows:

```
assets:
    sounds:
        default:
            load: preload
        voice:
            load: preload
            track: voice
            ducking:
              target: music
              delay: 0
              attack: 0.3 sec
              attenuation: 0.45
              release_point: 0.5 sec
              release: 1.0 sec
```
