### ISSUE TITLE
KeyError 'action' - in attract mode show

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#37]
Trying to run attract show, get the following crash for each slide in the show:

"  File "c:\python34\lib\site-packages\mpfmc\config_players\slide_player.py", line 163, in play
   if s['action'] == 'play':
KeyError: 'action'"

attract.yaml:
```
#config_version=4
mode:
  priority: 10000

show_player:
  mode_attract_started:
    attract_dmd_loop:
      action: play
      loops: -1
      speed: 1
    lsb_sweep:
      loops: -1
      speed: 6         

  mode_attract_stopped:
    attract_dmd_loop:
      action: stop
    lsb_sweep:
      action: stop
```

show file -
attract_dmd_loop.yaml

```
# show_version=4
- time: 0
  slides:
    attract_dmd_loop_slide_1:
    - type: text
      text: (machine|score1_label)
      style: tall_title
      font_size: 48
      anchor_y: top
      y: top
    - type: text
      text: (machine|score1_name) (machine|score1_value)
      style: tall_title
      font_size: 48
      number_grouping: true

- time: '+3'
  slides:
    attract_dmd_loop_slide_2:
    - type: text
      text: (machine|player1_score)
      color: yellow
      style: tall_title
      font_size: 48
      number_grouping: true
      min_digits: 2
      anchor_y: top
      anchor_x: left
      x: left+20
      y: top+0
    - type: text
      text: (machine|player2_score)
      color: yellow
      style: tall_title
      font_size: 48
      anchor_y: top
      anchor_x: right
      number_grouping: true
      min_digits: 2
      x: right-20
      y: top+0
    - type: text
      text: (machine|player3_score)
      color: yellow
      style: tall_title
      font_size: 48
      anchor_y: bottom
      anchor_x: left
      x: left+20
      y: bottom+5
      number_grouping: true
      min_digits: 2
    - type: text
      text: (machine|player4_score)
      color: yellow
      style: tall_title
      font_size: 48
      anchor_y: bottom
      anchor_x: right
      x: right-20
      y: bottom+5
      number_grouping: true
      min_digits: 2
    - type: text
      style: tall_title
      font_size: 36
      text: (machine|credits_string)
      color: magenta
      anchor_y: bottom
      y: bottom
- time: '+3'
  slides:
    attract_dmd_loop_slide_3:
      widgets:
      - type: image
        image: fast_pinball_logo_black_960
      transition:
        type: move_out
        duration: 1s
        direction: right

- time: '+3'
  slides:
    attract_dmd_loop_slide_4:
      widgets:
      - type: image
        image: Mission-Pinball-Logo-with-Script-200
      transition:
        type: move_out
        duration: 1s
        direction: left

- time: '+4'
  slides:
    attract_dmd_loop_slide_5:
      widgets:    
        - type: image
          image: fast_pinball_logo_black_960
          z: 25
 #       - type: video
 #         video: welcome
 #         z: 10
 #       - type: image
 #         image: mask2
 #         z: 20  


- time: '+8'
  slides:
    attract_dmd_loop_slide_6:
      widgets:
      - type: image
        image: title
      
- time: '+4'
  slides:
    attract_dmd_loop_slide_7:
    - type: text
      style: nightmare_l
      text: PRESS START
      color: lime
      animations:
        entrance:
        - property: opacity
          value: 1
          duration: 0.5s
        - property: opacity
          value: 0
          duration: 0.5s
          repeat: true
    - type: text
      style: tall_title
      font_size: 36
      text: (machine|credits_string)
      anchor_y: bottom


      y: bottom
- time: '+4'
```
