### ISSUE TITLE
slide set to expire, never does when interrupted 

### ISSUE THREAD

**Issue by MarkInc666** [missionpinball/mpf-mc#39]
3 slides with a mode.
show Slide A  (expire: 5s)
at 3s, show Slide B (countdown slide ~ 8 seconds)
show remove Slide B & Slide C (expire: 5s)
5s, Slide A appears, never expires

```
# config_version=4
# n2

#Mystery

mode:
  start_events: player_turn_start
  stop_events: game_ending
  code: Mystery.Mystery
  priority: 1800


slide_player:
  mystery_award_ready: slide_74
  mystery_award_selected_1: 
    slide_75:
      action: play
    slide_76:
      action: remove
  mystery_award_selection_countdown: slide_76
  
  
sound_player:
  mystery_sfx: cat_squeeze
    
slides:
  slide_74:
    widgets:    
      - type: video
        video: paperweb
      - type: image
        image: mask2
      - type: text
        style: tall_title
        font_size: 108
        text: YOUR AWARD IS READY
        anchor_y: top
        y: top
    expire: 5s    

  slide_75:
    widgets:  
      - type: video
        video: extraballmovie
      - type: image
        image: mask2
      - type: text
        style: tall_title
        font_size: 108
        text: (value)
        anchor_y: bottom
        y: bottom
      - type: text
        style: tall_title
        font_size: 108
        text: YOUR AWARD
        anchor_y: top
        y: top
    expire: 5s    
    
  slide_76:
    widgets:    
      - type: text
        style: tall_title
        font_size: 108
        text: CHOOSE YOUR AWARD
        anchor_y: top
        y: top
      - type: text
        style: tall_title
        font_size: 108
        text: (v1) (v2) (v3) (v4)
      - type: text
        style: tall_title
        font_size: 108
        anchor_y: bottom
        text: (value)
        y: bottom
```
