### ISSUE TITLE
outline_color bug or something else?

### ISSUE THREAD

**Issue by Pucksnok** [missionpinball/mpf-mc#456]
Hello.
For now I use Ubuntu for my coding and I think I have stumbled upon a bug with outline_color. I runt latest dev, 0.57 with Python 3.10.

I use widget_styles and have tested the outline_color and outline_width, it works great in the same slide as long as I use the **same** "color:" for all my text.
As soon I change the regular font-color to something else (so I use two colors), both the font and outline_color gets the same color on the second one, it then go for the font-color for both.
If I use the same font color I can use any outline_color without issues. I have also tried with different fonts, removing font choice completely etc.

As an example:

(If I use the below code in the same slide, the widget_style attract_mode_high_score_display_label works properly, the text is white and have a black outline. attract_mode_high_score_display_name is set to give the font a black color and white outline, BOTH font and outline gets black. If I try any other font color, for example yellow both the font and color_outline gets yellow).

          - type: Text
            text: (machine|score1_label)
            style: attract_mode_high_score_display_label
            y: top-200   
          - type: Text
            text: (machine|score1_name)
            style: attract_mode_high_score_display_name
            y: top-200

widget_styles:
attract_mode_high_score_display_label:
        font_size: 80
        anchor_x: right
        anchor_y: center
        x: center-3100
        font_name: arial
        color: white
        outline_color: black
        outline_width: 2
    attract_mode_high_score_display_name:
        font_size: 70
        anchor_x: right
        anchor_y: center
        x: center-2900
        color: black
        font_name: Impact
        outline_color: white
        outline_width: 2

**Comment by Pucksnok** [comment]
![20231213_235539.jpg](https://github.com/missionpinball/mpf-mc/assets/84498221/873a683e-1215-4740-bf8f-f086c9e0727c)

How the above code looks.

**Comment by Pucksnok** [comment]
Tried this in a completely new setup. Same problem exist there, as soon the font colors differs in the same slide the the outline_color fails to set the color correctly.

**Comment by gbouthenot** [comment]
I have the same problem with mpf 0.57.3
since mpf-mc is deprecated, I don't think this will be ever fixed.

**Comment by gbouthenot** [comment]
I found this : https://gamedev.stackexchange.com/questions/119642/how-to-use-sdl-ttfs-outlines

This appears that SDL2 cannot have a text outline color with a color different that the color of the text.

To have a text widget, with a different outilne_color, you'll have to do something like this:

```yaml
slides:
  my_slide:
    widgets:
      - type: text
        text: "my fancy text"
        font_size: 100
        x: 50%
        y: 50%
        color: 'ff0000'
        font_name: Arial
        z: 2
      - type: text
        text: "my fancy text"
        font_size: 100
        x: 50%
        y: 50%
        color: '00ff00'
        font_name: Arial
        outline_width: 5
        z: 2
```

It's two widget, one with outline and another one on top of it without outline.

It renders like this:

<img width="211" height="53" alt="Image" src="https://github.com/user-attachments/assets/f2c243c2-5ac5-4842-910d-fe8bb7b68a6c" />
