### ISSUE TITLE
animations don't take correct initial position

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#58]
```
 widget_h_shock:
     - type: image
       image: shock
       y: 120
       x: 75
       animations:
         entrance:
           - property: y
             value: 80
             duration: 5000ms
             timing: after_previous
           - property: opacity
             value: 1
             duration: 5000ms
             timing: after_previous
           - property: y
             value: 120
             duration: 5000ms
             timing: after_previous
       expire: 16s    
```

-  animation not working as expected
- shock image is supposed to be off screen (above) and then move down to 80, wait, then move back up off screen
- it's not starting at 120.  It looks like it starts at 0 (bottom of screen)
- animations are not taking the initial x/y positions
- above example was at the correct x,y location (75,120), but when animation starts, the y value resets to 0
