### ISSUE TITLE
dynamic widgets don't work with negative z values

### ISSUE THREAD

**Issue by toomanybrians** [missionpinball/mpf-mc#75]
```
widget_player:
  bug_hit_0: 
    widget_80:
      widget_settings:        
        expire: 750ms
        z: -1
  
widgets:
    widget_80:  
      - type: text
        x: 45
        y: 55
        style: tall_title
        font_size: 32
        text: SPLAT!
        color: red
        animations:
            add_to_slide:
            - property: opacity
              value: 1.0
              duration: 250ms
              timing: after_previous
            - property: y
              value: 0
              duration: 500ms
              timing: after_previous
            - property: opacity
              value: 0.0
              duration: 500ms
              timing: with_previous
```
Widget doesn't appear?
